version: "2"

services:
  wildfly:
    image: docker.io/bitnami/wildfly:27
    ports:
      - '8080:8080'
      - '9990:9990'
    volumes:
      - /path/to/standalone.xml:/bitnami/wildfly/configuration/standalone.xml:ro
      - 'wildfly_data:/bitnami'
    environment:
      - WILDFLY_USERNAME=my_user
      - WILDFLY_PASSWORD=my_password
  postgres:
    image: "postgres:15.2-alpine3.17"

volumes:
  wildfly_data:
    driver: local